version: '3'
services:
  # fluentd-stack-easy-ver0.0.12-nginx_d:
  #   build: "${PWD}/nginx_d/"
  #   image: nginx:1.10
  #   ports:
  #     # ホスト:コンテナ
  #     - "8080:80"
  #   container_name: fluentd-stack-easy-ver0.0.12-nginx_d
  #   volumes:
  #     - ./nginx_d/log:/var/log/nginx
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: "localhost:24222"
  #       tag: "nginx.{{.Name}}"
  #       fluentd-async-connect: "true"

  fluentd-stack-easy-ver0.0.12-app_d:
    build: "${PWD}/app_d/"
    ports:
      # ホスト:コンテナ
      - "8080:8000"
    container_name: fluentd-stack-easy-ver0.0.12-app_d
    volumes:
      - ${PWD}/app_d/api:/usr/src/server
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24222"
        tag: "app.{{.Name}}"
        fluentd-async-connect: "true"
    
  fluentd-stack-easy-ver0.0.12-fluent_d:
    image: fluent/fluentd:latest
    # build: ./fluent_d/
    restart: always
    container_name: fluentd-stack-easy-ver0.0.12-fluent_d
    command: >
      /usr/bin/fluentd -c /fluentd/etc/fluent.conf -v
    volumes:
      - ${PWD}/fluent_d/config/fluent.conf:/fluentd/etc/fluent.conf
      - ${PWD}/fluent_d/log:/fluentd/log
    ports:
      - "24222:24224"

  
